# Fichier de configuration des containers de DOCKER

version: '3.7'

services:
  app:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build: ./docker
    image: chialab/php-dev:7.2-apache
    volumes:
      - ${PWD}/www:/var/www
    ports:
      - "${CONTAINER_PORT}:80"
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env

  mysql:
    container_name:  ${CONTAINER_MYSQL}
    restart: unless-stopped
    image: mariadb
    networks: 
      - ${DOCKER_NETWORK}
    env_file:
      - .env
  mail:
    container_name:  ${CONTAINER_NAME}.mailcatcher
    restart: unless-stopped
    image: tophfr/mailcatcher
    ports:
      - ${PORT_MAIL}:1080
    networks: 
      - ${DOCKER_NETWORK}
    env_file:
      - .env

networks: 
  dt-dev.site:
    driver: bridge
